name: Workflow Preprocessing

on:
  workflow_dispatch:
  push:
    paths:
      - data_raw/**

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: Run Preprocessing
        run: |
          python preprocessing/automate_AssasaSalma.py \
            --input_path data_raw/python-learning-performance_raw.csv \
            --target_col passed_exam \
            --identifier_col student_id \
            --output_path preprocessing/python-learning-performance_preprocessing.csv

      - name: Upload Processed Dataset
        uses: actions/upload-artifact@v4
        with:
          name: python-learning-performance_preprocessing
          path: preprocessing/python-learning-performance_preprocessing.csv
  
